---
- name: Include tasks for role
  ansible.builtin.include_tasks:
    file: "{{ file }}"
  loop:
    - 'swap-disable.yml'
    - 'kernel-setup.yml'
    - 'runc-and-cni-install.yml'
    - 'containerd-install.yml'
    - 'k8s-components-install.yml'
    - 'cluster-setup.yml'
  loop_control:
    loop_var: file
